backup_settings:
  source_directories:
    - path: "/Users/nirsixadmin/Desktop/SvitUA/svituawww.github.io"
      name: "website"
      exclude_patterns:
        - "*.log"
        - "node_modules/"
        - ".git/"
      exclude_dir:
        - "uploads1"
        - "uploads_old"
        - "media"        
    - path: "/Users/nirsixadmin/Desktop/SvitUA/ptb_parser"
      name: "parser"
      exclude_patterns:
        - "__pycache__/"
        - "*.pyc"
      exclude_dir:
        - "tests"
    - path: "/Users/nirsixadmin/Desktop/SvitUA/deployment"
      name: "deployment"
      exclude_patterns:
        - "logs/"
        - "temp/"
      exclude_dir:
        - "backups"
    - path: "/Users/nirsixadmin/Desktop/SvitUA/cms_php_custom"
      name: "cms_php_custom"
    - path: "/Users/nirsixadmin/Desktop/Python/scrab_test"
      name: "jobbspranget_scraber"
      exclude_patterns:
        - "*.log"
      exclude_dir:
        - ".venv"
        - "__pycache__"
    - path: "/Users/nirsixadmin/Desktop/ScanAndWeb"
      name: "ScanAndWebBank"
      exclude_patterns:
        - "*.log"
        - "*.tmp"
      exclude_dir:
        - "venv"
        - "__pycache__"

  backup_destination:
    base_path: "/Users/nirsixadmin/Desktop/SvitUA/backups/"
    naming_pattern: "{timestamp}_{commit_hash}_{name}"
    
  compression:
    format: "zip"
    compression_level: 6
    
  metadata:
    include_git_info: true
    include_file_hashes: true
    include_size_info: true
